-- Permissions based on HR_Authentication_Template.xlsx and WFM_Authentication_Template.xlsx
-- This file seeds all permissions referenced in the role templates

-- Clear existing permissions
DELETE FROM permissions;

-- Insert all permissions referenced in the templates
INSERT INTO permissions (id, name, resource, action, description, module, "createdAt") VALUES
    -- System permissions (ADMIN module)
    (uuid_generate_v4(), 'users:CREATE', 'users', 'CREATE', 'Create users', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'users:READ', 'users', 'READ', 'Read users', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'users:UPDATE', 'users', 'UPDATE', 'Update users', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'users:DELETE', 'users', 'DELETE', 'Delete users', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'roles:CREATE', 'roles', 'CREATE', 'Create roles', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'roles:READ', 'roles', 'READ', 'Read roles', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'roles:UPDATE', 'roles', 'UPDATE', 'Update roles', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'roles:DELETE', 'roles', 'DELETE', 'Delete roles', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'permissions:CREATE', 'permissions', 'CREATE', 'Create permissions', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'permissions:READ', 'permissions', 'READ', 'Read permissions', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'permissions:UPDATE', 'permissions', 'UPDATE', 'Update permissions', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'permissions:DELETE', 'permissions', 'DELETE', 'Delete permissions', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'user_roles:CREATE', 'user_roles', 'CREATE', 'Create user roles', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'user_roles:READ', 'user_roles', 'READ', 'Read user roles', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'user_roles:UPDATE', 'user_roles', 'UPDATE', 'Update user roles', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'user_roles:DELETE', 'user_roles', 'DELETE', 'Delete user roles', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'role_permissions:CREATE', 'role_permissions', 'CREATE', 'Create role permissions', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'role_permissions:READ', 'role_permissions', 'READ', 'Read role permissions', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'role_permissions:UPDATE', 'role_permissions', 'UPDATE', 'Update role permissions', 'ADMIN', NOW()),
    (uuid_generate_v4(), 'role_permissions:DELETE', 'role_permissions', 'DELETE', 'Delete role permissions', 'ADMIN', NOW()),

    -- HR permissions (HR module)
    (uuid_generate_v4(), 'employees:CREATE', 'employees', 'CREATE', 'Create employees', 'HR', NOW()),
    (uuid_generate_v4(), 'employees:READ', 'employees', 'READ', 'Read employees', 'HR', NOW()),
    (uuid_generate_v4(), 'employees:UPDATE', 'employees', 'UPDATE', 'Update employees', 'HR', NOW()),
    (uuid_generate_v4(), 'employees:DELETE', 'employees', 'DELETE', 'Delete employees', 'HR', NOW()),
    (uuid_generate_v4(), 'departments:CREATE', 'departments', 'CREATE', 'Create departments', 'HR', NOW()),
    (uuid_generate_v4(), 'departments:READ', 'departments', 'READ', 'Read departments', 'HR', NOW()),
    (uuid_generate_v4(), 'departments:UPDATE', 'departments', 'UPDATE', 'Update departments', 'HR', NOW()),
    (uuid_generate_v4(), 'departments:DELETE', 'departments', 'DELETE', 'Delete departments', 'HR', NOW()),
    (uuid_generate_v4(), 'positions:CREATE', 'positions', 'CREATE', 'Create positions', 'HR', NOW()),
    (uuid_generate_v4(), 'positions:READ', 'positions', 'READ', 'Read positions', 'HR', NOW()),
    (uuid_generate_v4(), 'positions:UPDATE', 'positions', 'UPDATE', 'Update positions', 'HR', NOW()),
    (uuid_generate_v4(), 'positions:DELETE', 'positions', 'DELETE', 'Delete positions', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_personal_info:CREATE', 'employee_personal_info', 'CREATE', 'Create employee personal info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_personal_info:READ', 'employee_personal_info', 'READ', 'Read employee personal info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_personal_info:UPDATE', 'employee_personal_info', 'UPDATE', 'Update employee personal info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_personal_info:DELETE', 'employee_personal_info', 'DELETE', 'Delete employee personal info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_contact_info:CREATE', 'employee_contact_info', 'CREATE', 'Create employee contact info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_contact_info:READ', 'employee_contact_info', 'READ', 'Read employee contact info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_contact_info:UPDATE', 'employee_contact_info', 'UPDATE', 'Update employee contact info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_contact_info:DELETE', 'employee_contact_info', 'DELETE', 'Delete employee contact info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_employment_info:CREATE', 'employee_employment_info', 'CREATE', 'Create employee employment info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_employment_info:READ', 'employee_employment_info', 'READ', 'Read employee employment info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_employment_info:UPDATE', 'employee_employment_info', 'UPDATE', 'Update employee employment info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_employment_info:DELETE', 'employee_employment_info', 'DELETE', 'Delete employee employment info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_insurance_info:CREATE', 'employee_insurance_info', 'CREATE', 'Create employee insurance info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_insurance_info:READ', 'employee_insurance_info', 'READ', 'Read employee insurance info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_insurance_info:UPDATE', 'employee_insurance_info', 'UPDATE', 'Update employee insurance info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_insurance_info:DELETE', 'employee_insurance_info', 'DELETE', 'Delete employee insurance info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_bank_info:CREATE', 'employee_bank_info', 'CREATE', 'Create employee bank info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_bank_info:READ', 'employee_bank_info', 'READ', 'Read employee bank info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_bank_info:UPDATE', 'employee_bank_info', 'UPDATE', 'Update employee bank info', 'HR', NOW()),
    (uuid_generate_v4(), 'employee_bank_info:DELETE', 'employee_bank_info', 'DELETE', 'Delete employee bank info', 'HR', NOW()),
    (uuid_generate_v4(), 'documents:CREATE', 'documents', 'CREATE', 'Create documents', 'HR', NOW()),
    (uuid_generate_v4(), 'documents:READ', 'documents', 'READ', 'Read documents', 'HR', NOW()),
    (uuid_generate_v4(), 'documents:UPDATE', 'documents', 'UPDATE', 'Update documents', 'HR', NOW()),
    (uuid_generate_v4(), 'documents:DELETE', 'documents', 'DELETE', 'Delete documents', 'HR', NOW()),
    (uuid_generate_v4(), 'notifications:CREATE', 'notifications', 'CREATE', 'Create notifications', 'HR', NOW()),
    (uuid_generate_v4(), 'notifications:READ', 'notifications', 'READ', 'Read notifications', 'HR', NOW()),
    (uuid_generate_v4(), 'notifications:UPDATE', 'notifications', 'UPDATE', 'Update notifications', 'HR', NOW()),
    (uuid_generate_v4(), 'notifications:DELETE', 'notifications', 'DELETE', 'Delete notifications', 'HR', NOW()),
    (uuid_generate_v4(), 'workflow_instances:CREATE', 'workflow_instances', 'CREATE', 'Create workflow instances', 'HR', NOW()),
    (uuid_generate_v4(), 'workflow_instances:READ', 'workflow_instances', 'READ', 'Read workflow instances', 'HR', NOW()),
    (uuid_generate_v4(), 'workflow_instances:UPDATE', 'workflow_instances', 'UPDATE', 'Update workflow instances', 'HR', NOW()),
    (uuid_generate_v4(), 'workflow_instances:DELETE', 'workflow_instances', 'DELETE', 'Delete workflow instances', 'HR', NOW()),
    (uuid_generate_v4(), 'clearance_process:CREATE', 'clearance_process', 'CREATE', 'Create clearance process', 'HR', NOW()),
    (uuid_generate_v4(), 'clearance_process:READ', 'clearance_process', 'READ', 'Read clearance process', 'HR', NOW()),
    (uuid_generate_v4(), 'clearance_process:UPDATE', 'clearance_process', 'UPDATE', 'Update clearance process', 'HR', NOW()),
    (uuid_generate_v4(), 'clearance_process:DELETE', 'clearance_process', 'DELETE', 'Delete clearance process', 'HR', NOW()),
    (uuid_generate_v4(), 'exit_interviews:CREATE', 'exit_interviews', 'CREATE', 'Create exit interviews', 'HR', NOW()),
    (uuid_generate_v4(), 'exit_interviews:READ', 'exit_interviews', 'READ', 'Read exit interviews', 'HR', NOW()),
    (uuid_generate_v4(), 'exit_interviews:UPDATE', 'exit_interviews', 'UPDATE', 'Update exit interviews', 'HR', NOW()),
    (uuid_generate_v4(), 'exit_interviews:DELETE', 'exit_interviews', 'DELETE', 'Delete exit interviews', 'HR', NOW()),

    -- WFM permissions (WFM module)
    (uuid_generate_v4(), 'agent_schedules:CREATE', 'agent_schedules', 'CREATE', 'Create agent schedules', 'WFM', NOW()),
    (uuid_generate_v4(), 'agent_schedules:READ', 'agent_schedules', 'READ', 'Read agent schedules', 'WFM', NOW()),
    (uuid_generate_v4(), 'agent_schedules:UPDATE', 'agent_schedules', 'UPDATE', 'Update agent schedules', 'WFM', NOW()),
    (uuid_generate_v4(), 'agent_schedules:DELETE', 'agent_schedules', 'DELETE', 'Delete agent schedules', 'WFM', NOW()),
    (uuid_generate_v4(), 'shift_templates:CREATE', 'shift_templates', 'CREATE', 'Create shift templates', 'WFM', NOW()),
    (uuid_generate_v4(), 'shift_templates:READ', 'shift_templates', 'READ', 'Read shift templates', 'WFM', NOW()),
    (uuid_generate_v4(), 'shift_templates:UPDATE', 'shift_templates', 'UPDATE', 'Update shift templates', 'WFM', NOW()),
    (uuid_generate_v4(), 'shift_templates:DELETE', 'shift_templates', 'DELETE', 'Delete shift templates', 'WFM', NOW()),
    (uuid_generate_v4(), 'activity_codes:CREATE', 'activity_codes', 'CREATE', 'Create activity codes', 'WFM', NOW()),
    (uuid_generate_v4(), 'activity_codes:READ', 'activity_codes', 'READ', 'Read activity codes', 'WFM', NOW()),
    (uuid_generate_v4(), 'activity_codes:UPDATE', 'activity_codes', 'UPDATE', 'Update activity codes', 'WFM', NOW()),
    (uuid_generate_v4(), 'activity_codes:DELETE', 'activity_codes', 'DELETE', 'Delete activity codes', 'WFM', NOW()),
    (uuid_generate_v4(), 'client_requirements:CREATE', 'client_requirements', 'CREATE', 'Create client requirements', 'WFM', NOW()),
    (uuid_generate_v4(), 'client_requirements:READ', 'client_requirements', 'READ', 'Read client requirements', 'WFM', NOW()),
    (uuid_generate_v4(), 'client_requirements:UPDATE', 'client_requirements', 'UPDATE', 'Update client requirements', 'WFM', NOW()),
    (uuid_generate_v4(), 'client_requirements:DELETE', 'client_requirements', 'DELETE', 'Delete client requirements', 'WFM', NOW()),
    (uuid_generate_v4(), 'leave_requests:CREATE', 'leave_requests', 'CREATE', 'Create leave requests', 'WFM', NOW()),
    (uuid_generate_v4(), 'leave_requests:READ', 'leave_requests', 'READ', 'Read leave requests', 'WFM', NOW()),
    (uuid_generate_v4(), 'leave_requests:UPDATE', 'leave_requests', 'UPDATE', 'Update leave requests', 'WFM', NOW()),
    (uuid_generate_v4(), 'leave_requests:DELETE', 'leave_requests', 'DELETE', 'Delete leave requests', 'WFM', NOW()),
    (uuid_generate_v4(), 'leave_types:CREATE', 'leave_types', 'CREATE', 'Create leave types', 'WFM', NOW()),
    (uuid_generate_v4(), 'leave_types:READ', 'leave_types', 'READ', 'Read leave types', 'WFM', NOW()),
    (uuid_generate_v4(), 'leave_types:UPDATE', 'leave_types', 'UPDATE', 'Update leave types', 'WFM', NOW()),
    (uuid_generate_v4(), 'leave_types:DELETE', 'leave_types', 'DELETE', 'Delete leave types', 'WFM', NOW()),
    (uuid_generate_v4(), 'employee_leave_balances:CREATE', 'employee_leave_balances', 'CREATE', 'Create employee leave balances', 'WFM', NOW()),
    (uuid_generate_v4(), 'employee_leave_balances:READ', 'employee_leave_balances', 'READ', 'Read employee leave balances', 'WFM', NOW()),
    (uuid_generate_v4(), 'employee_leave_balances:UPDATE', 'employee_leave_balances', 'UPDATE', 'Update employee leave balances', 'WFM', NOW()),
    (uuid_generate_v4(), 'employee_leave_balances:DELETE', 'employee_leave_balances', 'DELETE', 'Delete employee leave balances', 'WFM', NOW()),
    (uuid_generate_v4(), 'shift_trade_requests:CREATE', 'shift_trade_requests', 'CREATE', 'Create shift trade requests', 'WFM', NOW()),
    (uuid_generate_v4(), 'shift_trade_requests:READ', 'shift_trade_requests', 'READ', 'Read shift trade requests', 'WFM', NOW()),
    (uuid_generate_v4(), 'shift_trade_requests:UPDATE', 'shift_trade_requests', 'UPDATE', 'Update shift trade requests', 'WFM', NOW()),
    (uuid_generate_v4(), 'shift_trade_requests:DELETE', 'shift_trade_requests', 'DELETE', 'Delete shift trade requests', 'WFM', NOW()),
    (uuid_generate_v4(), 'capacity_plans:CREATE', 'capacity_plans', 'CREATE', 'Create capacity plans', 'WFM', NOW()),
    (uuid_generate_v4(), 'capacity_plans:READ', 'capacity_plans', 'READ', 'Read capacity plans', 'WFM', NOW()),
    (uuid_generate_v4(), 'capacity_plans:UPDATE', 'capacity_plans', 'UPDATE', 'Update capacity plans', 'WFM', NOW()),
    (uuid_generate_v4(), 'capacity_plans:DELETE', 'capacity_plans', 'DELETE', 'Delete capacity plans', 'WFM', NOW()),
    (uuid_generate_v4(), 'accounts:CREATE', 'accounts', 'CREATE', 'Create accounts', 'WFM', NOW()),
    (uuid_generate_v4(), 'accounts:READ', 'accounts', 'READ', 'Read accounts', 'WFM', NOW()),
    (uuid_generate_v4(), 'accounts:UPDATE', 'accounts', 'UPDATE', 'Update accounts', 'WFM', NOW()),
    (uuid_generate_v4(), 'accounts:DELETE', 'accounts', 'DELETE', 'Delete accounts', 'WFM', NOW()),
    (uuid_generate_v4(), 'lobs:CREATE', 'lobs', 'CREATE', 'Create LOBs', 'WFM', NOW()),
    (uuid_generate_v4(), 'lobs:READ', 'lobs', 'READ', 'Read LOBs', 'WFM', NOW()),
    (uuid_generate_v4(), 'lobs:UPDATE', 'lobs', 'UPDATE', 'Update LOBs', 'WFM', NOW()),
    (uuid_generate_v4(), 'lobs:DELETE', 'lobs', 'DELETE', 'Delete LOBs', 'WFM', NOW()),

    -- Common permissions (SYSTEM module)
    (uuid_generate_v4(), 'reports:READ', 'reports', 'READ', 'Read reports', 'SYSTEM', NOW()),
    (uuid_generate_v4(), 'audit_logs:READ', 'audit_logs', 'READ', 'Read audit logs', 'SYSTEM', NOW());

-- Verify permissions
SELECT 
    resource,
    action,
    COUNT(*) as count
FROM permissions 
GROUP BY resource, action
ORDER BY resource, action;