# People Operation and Management System - Application Services
# This file contains only the application services (frontend, backend, nginx)
# For VM deployment where database is on a separate VM

version: '3.8'

services:
  # Frontend Service (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: ../Dockerfile.frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4000
      - NEXT_PUBLIC_APP_NAME=People Operation and Management
      - NEXT_PUBLIC_APP_VERSION=1.0.0
    depends_on:
      - backend
    networks:
      - people-ops-network
    restart: unless-stopped

  # Backend Service (NestJS)
  backend:
    build:
      context: ./backend
      dockerfile: ../Dockerfile.backend
    ports:
      - '4000:4000'
    env_file:
      - .env.app
    networks:
      - people-ops-network
    restart: unless-stopped

  # NGINX Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - people-ops-network
    restart: unless-stopped

# Custom network for service communication
networks:
  people-ops-network:
    driver: bridge
